
// Objective-C API for talking to the following Go packages
//
//	github.com/idena-network/idena-go/node
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Node_FRAMEWORK_H__
#define __Node_FRAMEWORK_H__

#include "Node.objc.h"
#include "Universe.objc.h"

#endif
